package be.hepl.benbear.sgbdapp;

import oracle.jdbc.OracleTypes;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;

import javax.swing.*;

public class SearchFrom {
    private JPanel panel1;
    private JList listResults;
    private JTextField textFieldSearch;
    private JButton buttonSearch;
    private JButton buttonHelp;

    public SearchFrom() throws Exception {
        $$$setupUI$$$();

        // Todo open database link
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con = DriverManager.getConnection("jdbc:oracle:thin:@178.32.41.4:8080:xe", "cb", "cb_bendemiscrazy");

        buttonSearch.addActionListener(e -> {
            char[] toParse = textFieldSearch.getText().toCharArray();

            try {
                CallableStatement cs = con.prepareCall("{? = call search.search(p_title => 'a')}");
                cs.registerOutParameter(1, OracleTypes.CURSOR);
                cs.execute();
                ResultSet rs = (ResultSet) cs.getObject(1);
                DefaultListModel model = new DefaultListModel();
                listResults.setModel(model);
                while (rs.next()) {
                    model.addElement(rs.getString("movie_title"));
                }
            } catch (SQLException e1) {
                e1.printStackTrace();
            }

            // Todo call the search procedure in the db to fill the list
        });
        buttonHelp.addActionListener(e -> {
            // Todo open help dialog as to how the hell you're supposed to enter criterias
        });
        listResults.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                if (e.getClickCount() == 2) {
                    // Todo open movie dialog passing the movie id as param (Todo write the dialog :L)
                }
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new CardLayout(0, 0));
        panel1.setPreferredSize(new Dimension(600, 400));
        final JSplitPane splitPane1 = new JSplitPane();
        splitPane1.setContinuousLayout(false);
        splitPane1.setDividerLocation(30);
        splitPane1.setEnabled(false);
        splitPane1.setOrientation(0);
        panel1.add(splitPane1, "Card1");
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        splitPane1.setLeftComponent(panel2);
        textFieldSearch = new JTextField();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(textFieldSearch, gbc);
        buttonSearch = new JButton();
        buttonSearch.setText("Search");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(buttonSearch, gbc);
        buttonHelp = new JButton();
        buttonHelp.setText("?");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(buttonHelp, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        splitPane1.setRightComponent(scrollPane1);
        listResults = new JList();
        scrollPane1.setViewportView(listResults);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
