CREATE ROLE MYROLE NOT IDENTIFIED;
GRANT ALTER SESSION TO MYROLE;
GRANT CREATE DATABASE LINK TO MYROLE;
GRANT CREATE SESSION TO MYROLE;
GRANT CREATE PROCEDURE TO MYROLE;
GRANT CREATE SEQUENCE TO MYROLE;
GRANT CREATE TABLE TO MYROLE;
GRANT CREATE TRIGGER TO MYROLE;
GRANT CREATE TYPE TO MYROLE;
GRANT CREATE SYNONYM TO MYROLE;
GRANT CREATE VIEW TO MYROLE;
GRANT CREATE JOB TO MYROLE;
GRANT CREATE MATERIALIZED VIEW TO MYROLE;
GRANT EXECUTE ON SYS.DBMS_LOCK TO MYROLE;
GRANT EXECUTE ON SYS.OWA_OPT_LOCK TO MYROLE;

CREATE USER CB IDENTIFIED BY dummy DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
ALTER USER CB QUOTA UNLIMITED ON USERS;
GRANT MYROLE TO CB;

CREATE USER CBB IDENTIFIED BY dummy DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
ALTER USER CBB QUOTA UNLIMITED ON USERS;
GRANT MYROLE TO CBB;
